#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

export LMMS_EVAL_PER_TYPE_LIMIT="${LMMS_EVAL_PER_TYPE_LIMIT:-5}"
export LMMS_EVAL_SAMPLE_SEED="${LMMS_EVAL_SAMPLE_SEED:-42}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export NUM_PROCESSES="${NUM_PROCESSES:-1}"

COMMON_OUTPUT_ROOT="${COMMON_OUTPUT_ROOT:-logs/$(TZ="America/New_York" date "+%Y%m%d")/vsibench_gen_vcd_ptb_preliminary_ablation_${LMMS_EVAL_PER_TYPE_LIMIT}_per_type}"
BASELINE_JSON="${BASELINE_JSON:-/root/autodl-tmp/projects/VLM-3R/thinking-in-space/logs/20260505/vsibench_5_per_type/0505_0310_vlm_3r_7b_qwen2_lora_5_per_type_vlm_3r_model_args_70e1b2/vsibench.json}"
COMPARE_TO_BASELINE="${COMPARE_TO_BASELINE:-true}"
PTB_PRELIMINARY_RATIO="${PTB_PRELIMINARY_RATIO:-0.08}"
PTB_PRELIMINARY_SELECTION_SCOPE="${PTB_PRELIMINARY_SELECTION_SCOPE:-global}"
PTB_PRELIMINARY_MIX_RATIO="${PTB_PRELIMINARY_MIX_RATIO:-0.70}"
PTB_PRELIMINARY_SHIFT_SIZE="${PTB_PRELIMINARY_SHIFT_SIZE:-1}"
PTB_PRELIMINARY_QUERY_MODE="${PTB_PRELIMINARY_QUERY_MODE:-question_cosine}"
CONTRAST_ALPHAS="${CONTRAST_ALPHAS:-[0.8]}"
BETA="${BETA:-0.02}"
RUN_SUFFIX="${RUN_SUFFIX:-ptb_prelim_once_r$(printf '%s' "${PTB_PRELIMINARY_RATIO}" | tr -d '.')_${PTB_PRELIMINARY_SELECTION_SCOPE}_m$(printf '%s' "${PTB_PRELIMINARY_MIX_RATIO}" | tr -d '.')_a$(printf '%s' "${CONTRAST_ALPHAS}" | tr -d '[],.')_b$(printf '%s' "${BETA}" | tr -d '.')}"

echo "Using 5-per-type baseline:"
echo "  BASELINE_JSON=${BASELINE_JSON}"
echo "  COMPARE_TO_BASELINE=${COMPARE_TO_BASELINE}"
echo "Running a single preliminary setting:"
echo "  RUN_SUFFIX=${RUN_SUFFIX}"
echo "  PTB_PRELIMINARY_RATIO=${PTB_PRELIMINARY_RATIO}"
echo "  PTB_PRELIMINARY_SELECTION_SCOPE=${PTB_PRELIMINARY_SELECTION_SCOPE}"
echo "  PTB_PRELIMINARY_QUERY_MODE=${PTB_PRELIMINARY_QUERY_MODE}"
echo "  PTB_PRELIMINARY_SHIFT_SIZE=${PTB_PRELIMINARY_SHIFT_SIZE}"
echo "  PTB_PRELIMINARY_MIX_RATIO=${PTB_PRELIMINARY_MIX_RATIO}"
echo "  CONTRAST_ALPHAS=${CONTRAST_ALPHAS}"
echo "  BETA=${BETA}"

RUN_SUFFIX="${RUN_SUFFIX}" \
OUTPUT_ROOT="${COMMON_OUTPUT_ROOT}" \
PTB_PRELIMINARY_RATIO="${PTB_PRELIMINARY_RATIO}" \
PTB_PRELIMINARY_SELECTION_SCOPE="${PTB_PRELIMINARY_SELECTION_SCOPE}" \
PTB_PRELIMINARY_QUERY_MODE="${PTB_PRELIMINARY_QUERY_MODE}" \
PTB_PRELIMINARY_SHIFT_SIZE="${PTB_PRELIMINARY_SHIFT_SIZE}" \
PTB_PRELIMINARY_MIX_RATIO="${PTB_PRELIMINARY_MIX_RATIO}" \
CONTRAST_ALPHAS="${CONTRAST_ALPHAS}" \
BETA="${BETA}" \
BASELINE_JSON="${BASELINE_JSON}" \
COMPARE_TO_BASELINE="${COMPARE_TO_BASELINE}" \
bash "${SCRIPT_DIR}/eval_vlm_3r_gen_vcd_ptb_preliminary_vsibench_5_per_type.sh"
